import React from "react"

declare global {
  interface Window {
    version: {
      env?: string
      api?: string
      commit?: string
    }
  }

  declare namespace JSXProps {
    type AElement = JSX.IntrinsicElements["a"]
    type AbbrElement = JSX.IntrinsicElements["abbr"]
    type AddressElement = JSX.IntrinsicElements["address"]
    type AreaElement = JSX.IntrinsicElements["area"]
    type ArticleElement = JSX.IntrinsicElements["article"]
    type AsideElement = JSX.IntrinsicElements["aside"]
    type AudioElement = JSX.IntrinsicElements["audio"]
    type BElement = JSX.IntrinsicElements["b"]
    type BaseElement = JSX.IntrinsicElements["base"]
    type BdiElement = JSX.IntrinsicElements["bdi"]
    type BdoElement = JSX.IntrinsicElements["bdo"]
    type BigElement = JSX.IntrinsicElements["big"]
    type BlockquoteElement = JSX.IntrinsicElements["blockquote"]
    type BodyElement = JSX.IntrinsicElements["body"]
    type BrElement = JSX.IntrinsicElements["br"]
    type ButtonElement = JSX.IntrinsicElements["button"]
    type CanvasElement = JSX.IntrinsicElements["canvas"]
    type CaptionElement = JSX.IntrinsicElements["caption"]
    type CiteElement = JSX.IntrinsicElements["cite"]
    type CodeElement = JSX.IntrinsicElements["code"]
    type ColElement = JSX.IntrinsicElements["col"]
    type ColgroupElement = JSX.IntrinsicElements["colgroup"]
    type DataElement = JSX.IntrinsicElements["data"]
    type DatalistElement = JSX.IntrinsicElements["datalist"]
    type DdElement = JSX.IntrinsicElements["dd"]
    type DelElement = JSX.IntrinsicElements["del"]
    type DetailsElement = JSX.IntrinsicElements["details"]
    type DfnElement = JSX.IntrinsicElements["dfn"]
    type DialogElement = JSX.IntrinsicElements["dialog"]
    type DivElement = JSX.IntrinsicElements["div"]
    type DlElement = JSX.IntrinsicElements["dl"]
    type DtElement = JSX.IntrinsicElements["dt"]
    type EmElement = JSX.IntrinsicElements["em"]
    type EmbedElement = JSX.IntrinsicElements["embed"]
    type FieldsetElement = JSX.IntrinsicElements["fieldset"]
    type FigcaptionElement = JSX.IntrinsicElements["figcaption"]
    type FigureElement = JSX.IntrinsicElements["figure"]
    type FooterElement = JSX.IntrinsicElements["footer"]
    type FormElement = JSX.IntrinsicElements["form"]
    type H1Element = JSX.IntrinsicElements["h1"]
    type H2Element = JSX.IntrinsicElements["h2"]
    type H3Element = JSX.IntrinsicElements["h3"]
    type H4Element = JSX.IntrinsicElements["h4"]
    type H5Element = JSX.IntrinsicElements["h5"]
    type H6Element = JSX.IntrinsicElements["h6"]
    type HeadElement = JSX.IntrinsicElements["head"]
    type HeaderElement = JSX.IntrinsicElements["header"]
    type HgroupElement = JSX.IntrinsicElements["hgroup"]
    type HrElement = JSX.IntrinsicElements["hr"]
    type HtmlElement = JSX.IntrinsicElements["html"]
    type IElement = JSX.IntrinsicElements["i"]
    type IframeElement = JSX.IntrinsicElements["iframe"]
    type ImgElement = JSX.IntrinsicElements["img"]
    type InputElement = JSX.IntrinsicElements["input"]
    type InsElement = JSX.IntrinsicElements["ins"]
    type KbdElement = JSX.IntrinsicElements["kbd"]
    type KeygenElement = JSX.IntrinsicElements["keygen"]
    type LabelElement = JSX.IntrinsicElements["label"]
    type LegendElement = JSX.IntrinsicElements["legend"]
    type LiElement = JSX.IntrinsicElements["li"]
    type LinkElement = JSX.IntrinsicElements["link"]
    type MainElement = JSX.IntrinsicElements["main"]
    type MapElement = JSX.IntrinsicElements["map"]
    type MarkElement = JSX.IntrinsicElements["mark"]
    type MenuElement = JSX.IntrinsicElements["menu"]
    type MenuitemElement = JSX.IntrinsicElements["menuitem"]
    type MetaElement = JSX.IntrinsicElements["meta"]
    type MeterElement = JSX.IntrinsicElements["meter"]
    type NavElement = JSX.IntrinsicElements["nav"]
    type NoindexElement = JSX.IntrinsicElements["noindex"]
    type NoscriptElement = JSX.IntrinsicElements["noscript"]
    type ObjectElement = JSX.IntrinsicElements["object"]
    type OlElement = JSX.IntrinsicElements["ol"]
    type OptgroupElement = JSX.IntrinsicElements["optgroup"]
    type OptionElement = JSX.IntrinsicElements["option"]
    type OutputElement = JSX.IntrinsicElements["output"]
    type PElement = JSX.IntrinsicElements["p"]
    type ParamElement = JSX.IntrinsicElements["param"]
    type PictureElement = JSX.IntrinsicElements["picture"]
    type PreElement = JSX.IntrinsicElements["pre"]
    type ProgressElement = JSX.IntrinsicElements["progress"]
    type QElement = JSX.IntrinsicElements["q"]
    type RpElement = JSX.IntrinsicElements["rp"]
    type RtElement = JSX.IntrinsicElements["rt"]
    type RubyElement = JSX.IntrinsicElements["ruby"]
    type SElement = JSX.IntrinsicElements["s"]
    type SampElement = JSX.IntrinsicElements["samp"]
    type ScriptElement = JSX.IntrinsicElements["script"]
    type SectionElement = JSX.IntrinsicElements["section"]
    type SelectElement = JSX.IntrinsicElements["select"]
    type SmallElement = JSX.IntrinsicElements["small"]
    type SourceElement = JSX.IntrinsicElements["source"]
    type SpanElement = JSX.IntrinsicElements["span"]
    type StrongElement = JSX.IntrinsicElements["strong"]
    type StyleElement = JSX.IntrinsicElements["style"]
    type SubElement = JSX.IntrinsicElements["sub"]
    type SummaryElement = JSX.IntrinsicElements["summary"]
    type SupElement = JSX.IntrinsicElements["sup"]
    type TableElement = JSX.IntrinsicElements["table"]
    type TemplateElement = JSX.IntrinsicElements["template"]
    type TbodyElement = JSX.IntrinsicElements["tbody"]
    type TdElement = JSX.IntrinsicElements["td"]
    type TextareaElement = JSX.IntrinsicElements["textarea"]
    type TfootElement = JSX.IntrinsicElements["tfoot"]
    type ThElement = JSX.IntrinsicElements["th"]
    type TheadElement = JSX.IntrinsicElements["thead"]
    type TimeElement = JSX.IntrinsicElements["time"]
    type TitleElement = JSX.IntrinsicElements["title"]
    type TrElement = JSX.IntrinsicElements["tr"]
    type TrackElement = JSX.IntrinsicElements["track"]
    type UElement = JSX.IntrinsicElements["u"]
    type UlElement = JSX.IntrinsicElements["ul"]
    type VarElement = JSX.IntrinsicElements["var"]
    type VideoElement = JSX.IntrinsicElements["video"]
    type WbrElement = JSX.IntrinsicElements["wbr"]
    type WebviewElement = JSX.IntrinsicElements["webview"]
    type SvgElement = JSX.IntrinsicElements["svg"]
    type AnimateElement = JSX.IntrinsicElements["animate"]
    type AnimateMotionElement = JSX.IntrinsicElements["animateMotion"]
    type AnimateTransformElement = JSX.IntrinsicElements["animateTransform"]
    type CircleElement = JSX.IntrinsicElements["circle"]
    type ClipPathElement = JSX.IntrinsicElements["clipPath"]
    type DefsElement = JSX.IntrinsicElements["defs"]
    type DescElement = JSX.IntrinsicElements["desc"]
    type EllipseElement = JSX.IntrinsicElements["ellipse"]
    type FeBlendElement = JSX.IntrinsicElements["feBlend"]
    type FeColorMatrixElement = JSX.IntrinsicElements["feColorMatrix"]
    type FeComponentTransferElement = JSX.IntrinsicElements["feComponentTransfer"]
    type FeCompositeElement = JSX.IntrinsicElements["feComposite"]
    type FeConvolveMatrixElement = JSX.IntrinsicElements["feConvolveMatrix"]
    type FeDiffuseLightingElement = JSX.IntrinsicElements["feDiffuseLighting"]
    type FeDisplacementMapElement = JSX.IntrinsicElements["feDisplacementMap"]
    type FeDistantLightElement = JSX.IntrinsicElements["feDistantLight"]
    type FeDropShadowElement = JSX.IntrinsicElements["feDropShadow"]
    type FeFloodElement = JSX.IntrinsicElements["feFlood"]
    type FeFuncAElement = JSX.IntrinsicElements["feFuncA"]
    type FeFuncBElement = JSX.IntrinsicElements["feFuncB"]
    type FeFuncGElement = JSX.IntrinsicElements["feFuncG"]
    type FeFuncRElement = JSX.IntrinsicElements["feFuncR"]
    type FeGaussianBlurElement = JSX.IntrinsicElements["feGaussianBlur"]
    type FeImageElement = JSX.IntrinsicElements["feImage"]
    type FeMergeElement = JSX.IntrinsicElements["feMerge"]
    type FeMergeNodeElement = JSX.IntrinsicElements["feMergeNode"]
    type FeMorphologyElement = JSX.IntrinsicElements["feMorphology"]
    type FeOffsetElement = JSX.IntrinsicElements["feOffset"]
    type FePointLightElement = JSX.IntrinsicElements["fePointLight"]
    type FeSpecularLightingElement = JSX.IntrinsicElements["feSpecularLighting"]
    type FeSpotLightElement = JSX.IntrinsicElements["feSpotLight"]
    type FeTileElement = JSX.IntrinsicElements["feTile"]
    type FeTurbulenceElement = JSX.IntrinsicElements["feTurbulence"]
    type FilterElement = JSX.IntrinsicElements["filter"]
    type ForeignObjectElement = JSX.IntrinsicElements["foreignObject"]
    type GElement = JSX.IntrinsicElements["g"]
    type ImageElement = JSX.IntrinsicElements["image"]
    type LineElement = JSX.IntrinsicElements["line"]
    type LinearGradientElement = JSX.IntrinsicElements["linearGradient"]
    type MarkerElement = JSX.IntrinsicElements["marker"]
    type MaskElement = JSX.IntrinsicElements["mask"]
    type MetadataElement = JSX.IntrinsicElements["metadata"]
    type MpathElement = JSX.IntrinsicElements["mpath"]
    type PathElement = JSX.IntrinsicElements["path"]
    type PatternElement = JSX.IntrinsicElements["pattern"]
    type PolygonElement = JSX.IntrinsicElements["polygon"]
    type PolylineElement = JSX.IntrinsicElements["polyline"]
    type RadialGradientElement = JSX.IntrinsicElements["radialGradient"]
    type RectElement = JSX.IntrinsicElements["rect"]
    type StopElement = JSX.IntrinsicElements["stop"]
    type SwitchElement = JSX.IntrinsicElements["switch"]
    type SymbolElement = JSX.IntrinsicElements["symbol"]
    type TextElement = JSX.IntrinsicElements["text"]
    type TextPathElement = JSX.IntrinsicElements["textPath"]
    type TspanElement = JSX.IntrinsicElements["tspan"]
    type UseElement = JSX.IntrinsicElements["use"]
    type ViewElement = JSX.IntrinsicElements["view"]
  }

  declare namespace ReactProps {
    type EventKey = string | number
    type WithChildren = { children?: React.ReactNode }
    type WithClassName = { className?: string }
    type WithStyle = { style?: React.CSSProperties }
    type Component = WithChildren & WithClassName & WithStyle
  }
}

export default global
